os:
  - linux

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3

branches:
  only:
    - master

script:
  - cd tests && make

notifications:
  email: false
